server:
  port: 8081
  tomcat:
    max-swallow-size: 52428800
    max-http-form-post-size: 52428800
spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/jobOffers?connectTimeoutMS=60000&socketTimeoutMS=60000

